name: Run Tests and Coverage
env:
  env_var: '${{ vars.CODECOV_TEST_VARIABLE_TOKEN }}-TYKONDO'

on: [push, pull_request]

jobs:
  build-python:
    env:
      local_var: 'LOOK HERE'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r api/requirements.txt
      - name: Run tests and collect coverage for calculator
        run: pytest --cov api.calculator --cov-report=xml:calculator-coverage.xml
      - name: Run tests and collect coverage for Smiles
        run: pytest --cov api.smiles --cov-report=xml:smiles-coverage.xml
      - name: Upload coverage reports to CodeCov using GitHub Action
        uses: codecov/codecov-action@v3