name: Run Tests and Coverage

on: [push]

env:
  env_var: ${{ vars.CODECOV_TEST_VARIABLE_TOKEN }}

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r api/requirements.txt
      - name: Execute Tests
        run: pytest --cov api/
      - name: Display Variables
        run: |
          echo "variable ${CODECOV_TOKEN}"
          echo "Secret ${CODECOV_SECRET}"
          echo "env var ${FROM_ENV}"
        env:
          CODECOV_TOKEN: ${{ vars.CODECOV_TEST_VARIABLE_TOKEN }}
          CODECOV_SECRET: ${{ secrets.CODECOV_TEST_SECRET_TOKEN }}
          FROM_ENV: ${{ env.env_var }}
