name: Run Tests and Coverage
env:
  env_var: '${{ vars.CODECOV_TEST_VARIABLE_TOKEN }}-TYKONDO'

on: [push]

jobs:
  build-python:
    env:
      local_var: 'LOOK HERE'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r api/requirements.txt
      - name: Execute Tests
        run: pytest --cov api/
      - name: Display Variables
        run: |
          echo "variable ${CODECOV_TOKEN}"
          echo "Secret ${CODECOV_SECRET}"
          echo "env var ${FROM_ENV} ${env_var}"
          echo "local var ${{ env.local_var }}"
          echo "local var $LOCAL"
        env:
          CODECOV_TOKEN: ${{ vars.CODECOV_TEST_VARIABLE_TOKEN }}
          CODECOV_SECRET: ${{ secrets.CODECOV_TEST_SECRET_TOKEN }}
          FROM_ENV: ${{ env.env_var }}
          LOCAL: ${{ env.local_var }}
