name: Enforce License Compliance

on:
  pull_request:
    branches: [main]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Merging...Done"
        - run: echo "SECRET ${{ secrets.CODECOV_TEST_SECRET_TOKEN }}"
        - run: echo "VARIABLE ${{ vars.CODECOV_TEST_VARIABLE_TOKEN }}"